[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]
live_config_reload = true

[window]
decorations = "buttonless"
opacity = 0.8
blur = true

[window.padding]
x = 25
y = 20

[font]
size = 19
normal.family = "MesloLGS Nerd Font Mono"

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "C", mods = "Command", action = "Copy" },
    { key = "V", mods = "Command", action = "Paste" },
    { key = "F", mods = "Command", action = "SearchForward" },
    { key = "N", mods = "Command", action = "CreateNewWindow" },
    { key = "H", mods = "Command", action = "Hide" },
]
